.\" finddeps-distmeta(1) manual page
.\" See COPYING and COPYRIGHT files for corresponding information.
.Dd September 3, 2023
.Dt FINDDEPSDISTMETA 1
.Os
.\" ==================================================================
.Sh NAME
.Nm finddepsdistmeta
.Nd parse Perl-module's distmeta file and find dependencies
.\" ==================================================================
.Sh SYNOPSIS
.Nm finddepsdistmeta
.Op Fl hv
.Op Ar file
.\" ==================================================================
.Sh DESCRIPTION
The
.Nm
utility parses so-called
.Dq distmeta
(CPAN distribution metadata) of Perl-module and find dependencies.
It shows dependencies that are in the core Perl distribution and
searches missing modules in the existing installed
.Dq p5-*
packages.
.Pp
.Nm
operates on packages' sources repository to search dependencies in the
packages' footprints, and therefore requires
.Xr pkgman 1 .
.Pp
The options are as follows:
.Bl -tag -width XXXXXXXXXXXXX
.It Fl v , Fl \&-version
Print version and exit.
.It Fl h , Fl \&-help
Print help and exit.
.El
.\" ==================================================================
.Sh EXAMPLES
The typical usage of
.Nm
is to call it from the Perl's module directory:
.Bd -literal -offset indent
cd /var/cache/pkgmk/sources/URI-5.17
finddepsdistmeta
.Ed
.Pp
Or to specify the location of
.Pa META.yml
file manually:
.Bd -literal -offset indent
finddepsdistmeta /var/cache/pkgmk/source/URI-5.17/META.yml
.Ed
.Pp
Another convenient way is to call
.Nm
from the
.Pa Pkgfile
when you're building the package:
.Bd -literal
build() {
        cd URI-$version

        finddepsdistmeta
        ...
}
.Ed
.Pp
So, you can check the output, fix
.Dq Depends on:
field and remove unnecessary call afterwards.
.\" ==================================================================
.Sh SEE ALSO
.Xr finddepslinked 1 ,
.Xr findredundantdeps 1
.\" ==================================================================
.Sh BUGS
Currently,
.Nm
parses only
.Pa META.yml
file, which is generated by
.Xr ExtUtils::MakeMaker 3pm .
The parsing of
.Pa META.json
isn't added yet.
.\" vim: cc=72 tw=70
.\" End of file.
