.\" finddisappeared(1) manual page
.\" See COPYING and COPYRIGHT files for corresponding information.
.Dd September 3, 2023
.Dt FINDDISAPPEARED 1
.Os
.\" ==================================================================
.Sh NAME
.Nm finddisappeared
.Nd find files that are owned by package manager but disappeared
.\" ==================================================================
.Sh SYNOPSIS
.Nm finddisappeared
.Op Fl r Ar rootdir
.Nm
.Op Fl v
.Nm
.Op Fl h
.\" ==================================================================
.Sh DESCRIPTION
The
.Nm
utility lists the files that are owned by package manager (listed in
the package database), but missing (somehow disappeared) on the actual
file system.
.Pp
The options are as follows:
.Bl -tag -width Ds
.It Fl r Ar rootdir , Fl -root Ns = Ns Ar rootdir
Specify an alternate root directory instead of the default
.Ql / .
.It Fl v , Fl \&-version
Print version and exit.
.It Fl h , Fl \&-help
Print help and exit.
.El
.\" ==================================================================
.Sh SEE ALSO
.Xr finddeps-distmeta 1 ,
.Xr finddeps-linked 1 ,
.Xr finddisowned 1 ,
.Xr findredundantdeps 1
.\" ==================================================================
.Sh AUTHORS
.An Martil Opel Aq Mt mo@obbl.net
.\" vim: cc=72 tw=70
.\" End of file.
