#!/bin/sh
# findredundantdeps - find (un)necessary dependencies of the package
# See COPYING and COPYRIGHT files for corresponding information.

######################################################################
# Findredundantdeps.                                                 #
######################################################################

findredundantdeps() {
	DEPS=$(pkgman dep --all "$1") || exit 3

	# Intentional.
	# shellcheck disable=2086
	pkgman dep --all --recursive --full "$1" |
		grep -E "($(echo $DEPS | tr ' ' '|'))$"
}

show_uniq() {
	tr ' ' '\n' | sort | uniq -u
}

######################################################################
# Command-line helpers.                                              #
######################################################################

print_help() {
	cat <<EOF
Usage: $ARGV0 [-u] pkgname
       $ARGV0 [-v]
       $ARGV0 [-h]
Find (un)necessary dependencies of the package.

  -u, --unique   print only unique (required) dependencies
  -v, --version  print version and exit
  -h, --help     print help and exit
EOF
}

print_version() {
	echo "$ARGV0 (pkgmaint) @VERSION@"
}

parse_options() {
	if ! _OPTS=$(getopt -a -n "$ARGV0" -l "$LOPTS" -o "$SOPTS" -- "$@"); then
		echo "Try '$ARGV0 --help' for more information." 1>&2
		exit 1
	fi
	eval set -- "$_OPTS"; unset _OPTS
	while true; do
		case $1 in
		-u| --unique) SHOW_UNIQ_CMD=show_uniq ;;
		-v|--version) print_version  ; exit 0 ;;
		-h|   --help) print_help     ; exit 0 ;;
		          --) shift          ; break  ;;
		esac
		shift
	done

	SHOW_UNIQ_CMD=${SHOW_UNIQ_CMD:-cat}
	PKGNAME=$*

	# Intentional word splitting.
	# shellcheck disable=SC2086
	set -- $PKGNAME

	case $# in
	1) ;; # all is ok, one argument is required
	0) echo "$ARGV0: missing argument" 1>&2
	   echo "Try '$ARGV0 --help' for more information." 1>&2
	   exit 1
	   ;;
	*) echo "$ARGV0: too many arguments" 1>&2
	   echo "Try '$ARGV0 --help' for more information." 1>&2
	   exit 1
	   ;;
	esac
}

main() {
	parse_options "$@"

	findredundantdeps "$PKGNAME" | $SHOW_UNIQ_CMD
}

######################################################################

# -e: Exit if command return status greater than 0
# -f: Disable globbing *?[]
set -ef

# Globals.
export LC_ALL=POSIX
readonly ARGV0="${0##*/}"
readonly LOPTS="unique,version,help"
readonly SOPTS="uvh"

######################################################################

main "$@"

# vim: cc=72 tw=70
# End of file.
