#!/bin/sh

dep() {
	DEPS=$(pkgman dep --all $1) || exit 1
	pkgman dep --all --recursive --full $1 | \
		egrep "($(echo $DEPS | tr ' ' '|'))$"
}

while [ $# -gt 0 ]; do
	case $1 in
	-u) UNIQ=1 ; shift ;;
	-*) echo "usage: ${0##*/} [-u] PKG" ; exit 1 ;;
	 *) PKG=$1 ; shift ;;
	esac
done

[ "$UNIQ" = 1 ] && dep $PKG | tr ' ' '\n' | sort | uniq -u || dep $PKG

# End of file.
